-- ============================================================================
--  TrendsMart — "verify before packing" notification copy
--
--  The in-app bell text for a new order is generated by DB triggers, so the
--  Roman Urdu verify notice has to live here too — otherwise merchants see the
--  reminder in push/UI but plain English in the bell.
-- ============================================================================

CREATE OR REPLACE FUNCTION public.notify_order_created()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  shop_owner uuid;
  merchant_title text;
  merchant_body text;
  buyer_body text;
  customer_label text;
  amount_label text;
BEGIN
  SELECT owner_id INTO shop_owner FROM public.shops WHERE id = NEW.shop_id;

  customer_label := COALESCE(NULLIF(btrim(NEW.customer_name), ''), 'Customer');
  amount_label := 'Rs. ' || round(COALESCE(NEW.total_amount, 0))::text;

  IF NEW.whatsapp_sent_at IS NULL THEN
    merchant_title := 'Naya order — confirm karna zaroori hai';
    merchant_body := customer_label || ' · ' || amount_label
      || ' — customer ne abhi WhatsApp par confirm nahi kiya. '
      || 'Pack ya deliver karne se pehle aik dafa confirm zaroor karein.';
  ELSE
    merchant_title := 'Naya order — ' || amount_label;
    merchant_body := customer_label || ' ne order place kiya hai (' || NEW.status || ').';
  END IF;

  IF shop_owner IS NOT NULL THEN
    PERFORM public.create_notification(
      shop_owner,
      'sale',
      merchant_title,
      merchant_body,
      '/dashboard/orders',
      NEW.id::text
    );
  END IF;

  IF NEW.customer_user_id IS NOT NULL THEN
    IF NEW.whatsapp_sent_at IS NULL THEN
      buyer_body := 'Order save ho gaya. Shop ko WhatsApp par bhej dein taake wo confirm kar sakein — '
        || 'ya iraada badal jaye to My Orders se cancel kar dein.';
    ELSE
      buyer_body := 'Aap ka order shop ko bhej diya gaya hai.';
    END IF;

    PERFORM public.create_notification(
      NEW.customer_user_id,
      'order',
      'Order place ho gaya — ' || amount_label,
      buyer_body,
      '/orders/tracking?orderId=' || NEW.id::text,
      NEW.id::text
    );
  END IF;

  RETURN NEW;
END;
$$;
