-- Auto-seed remaining built-in sub-categories for all shop types
-- Mirrors lib/defaultSubCategories.ts (safe to re-run)

INSERT INTO public.sub_categories (category, name, slug, description, icon, sort_order, is_others) VALUES
  ('Fruits & Vegetables', 'Fresh Fruits', 'fresh-fruits', 'Seasonal fruits', '🍎', 1, false),
  ('Fruits & Vegetables', 'Fresh Vegetables', 'fresh-vegetables', 'Daily sabzi', '🥬', 2, false),
  ('Fruits & Vegetables', 'Leafy Greens', 'leafy-greens', 'Saag and salad leaves', '🥗', 3, false),
  ('Fruits & Vegetables', 'Dry Fruits & Nuts', 'dry-fruits-nuts', 'Almonds, dates, nuts', '🥜', 4, false),
  ('Fruits & Vegetables', 'Exotic & Imported', 'exotic-imported', 'Imported produce', '🥭', 5, false),
  ('Fruits & Vegetables', 'Others / General', 'fruits-vegetables-others', 'Other produce', '📦', 999, true),
  ('Bakery & Sweets', 'Cakes & Pastries', 'cakes-pastries', 'Cakes and bakery sweets', '🎂', 1, false),
  ('Bakery & Sweets', 'Bread & Bun', 'bread-bun', 'Fresh bread', '🍞', 2, false),
  ('Bakery & Sweets', 'Mithai & Desi Sweets', 'mithai-desi', 'Traditional sweets', '🍬', 3, false),
  ('Bakery & Sweets', 'Cookies & Rusk', 'cookies-rusk', 'Biscuits and rusk', '🍪', 4, false),
  ('Bakery & Sweets', 'Custom Orders', 'custom-orders', 'Made-to-order bakery', '✨', 5, false),
  ('Bakery & Sweets', 'Others / General', 'bakery-sweets-others', 'Other bakery items', '📦', 999, true),
  ('Pharmacy & Medical', 'Medicines', 'medicines', 'OTC and prescription', '💊', 1, false),
  ('Pharmacy & Medical', 'First Aid', 'first-aid', 'Bandages and kits', '🩹', 2, false),
  ('Pharmacy & Medical', 'Vitamins & Supplements', 'vitamins-supplements', 'Health supplements', '🧴', 3, false),
  ('Pharmacy & Medical', 'Baby Care', 'pharma-baby-care', 'Baby health products', '🍼', 4, false),
  ('Pharmacy & Medical', 'Personal Care', 'pharma-personal-care', 'Hygiene products', '🧼', 5, false),
  ('Pharmacy & Medical', 'Others / General', 'pharmacy-medical-others', 'Other medical items', '📦', 999, true),
  ('Home Maintenance & Repair', 'Plumbing', 'plumbing', 'Plumber services', '🚰', 1, false),
  ('Home Maintenance & Repair', 'Electrical', 'electrical', 'Electrician services', '⚡', 2, false),
  ('Home Maintenance & Repair', 'AC & Cooling', 'ac-cooling', 'AC repair and install', '❄️', 3, false),
  ('Home Maintenance & Repair', 'Carpentry & Furniture', 'carpentry-furniture', 'Wood and furniture work', '🪵', 4, false),
  ('Home Maintenance & Repair', 'Painting & Renovation', 'painting-renovation', 'Paint and remodel', '🖌️', 5, false),
  ('Home Maintenance & Repair', 'Others / General', 'home-maintenance-repair-others', 'Other repair services', '📦', 999, true),
  ('Security & Surveillance', 'CCTV Cameras', 'cctv-cameras', 'Camera systems', '📹', 1, false),
  ('Security & Surveillance', 'Alarm Systems', 'alarm-systems', 'Security alarms', '🚨', 2, false),
  ('Security & Surveillance', 'Access Control', 'access-control', 'Locks and entry systems', '🔐', 3, false),
  ('Security & Surveillance', 'Installation & Setup', 'security-installation', 'Install services', '🛠️', 4, false),
  ('Security & Surveillance', 'Others / General', 'security-surveillance-others', 'Other security items', '📦', 999, true),
  ('Tech & IT Services', 'Laptop & PC Repair', 'laptop-pc-repair', 'Computer repair', '🖥️', 1, false),
  ('Tech & IT Services', 'Mobile Repair', 'mobile-repair', 'Phone repair', '📱', 2, false),
  ('Tech & IT Services', 'Networking & WiFi', 'networking-wifi', 'Network setup', '📶', 3, false),
  ('Tech & IT Services', 'Software & Web', 'software-web', 'Software and websites', '🌐', 4, false),
  ('Tech & IT Services', 'Data Recovery', 'data-recovery', 'Recover lost data', '💾', 5, false),
  ('Tech & IT Services', 'IT Support Packages', 'it-support-packages', 'Ongoing IT support', '🧰', 6, false),
  ('Tech & IT Services', 'Others / General', 'tech-it-services-others', 'Other IT services', '📦', 999, true),
  ('Personal & Professional Services', 'Tutoring & Coaching', 'tutoring-coaching', 'Education services', '🎓', 1, false),
  ('Personal & Professional Services', 'Beauty & Salon', 'beauty-salon', 'Salon services', '💇', 2, false),
  ('Personal & Professional Services', 'Cleaning Services', 'cleaning-services', 'Home and office cleaning', '✨', 3, false),
  ('Personal & Professional Services', 'Event & Photography', 'event-photography', 'Events and photos', '📸', 4, false),
  ('Personal & Professional Services', 'Legal & Accounting', 'legal-accounting', 'Professional services', '📑', 5, false),
  ('Personal & Professional Services', 'Others / General', 'personal-professional-services-others', 'Other services', '📦', 999, true),
  ('Handmade & Crafts', 'Handmade Decor', 'handmade-decor', 'Handcrafted decor', '🏺', 1, false),
  ('Handmade & Crafts', 'Jewelry & Accessories', 'handmade-jewelry', 'Handmade jewelry', '💍', 2, false),
  ('Handmade & Crafts', 'Custom Gifts', 'custom-gifts', 'Personalized gifts', '🎁', 3, false),
  ('Handmade & Crafts', 'Art & Paintings', 'art-paintings', 'Original art', '🖼️', 4, false),
  ('Handmade & Crafts', 'Others / General', 'handmade-crafts-others', 'Other crafts', '📦', 999, true),
  ('Fast Food & Restaurants', 'Burgers', 'burgers', 'Burgers and smash burgers', '🍔', 1, false),
  ('Fast Food & Restaurants', 'Shawarma & Rolls', 'shawarma-rolls', 'Shawarma, wraps, rolls', '🌯', 2, false),
  ('Fast Food & Restaurants', 'Deals & Combos', 'deals-combos', 'Family deals and meal boxes', '🔥', 3, false),
  ('Fast Food & Restaurants', 'Desi & BBQ', 'desi-bbq', 'Biryani, karahi, BBQ', '🍖', 4, false),
  ('Fast Food & Restaurants', 'Pizza & Pasta', 'pizza-pasta', 'Pizza and pasta', '🍕', 5, false),
  ('Fast Food & Restaurants', 'Fries & Sides', 'fries-sides', 'Fries and sides', '🍟', 6, false),
  ('Fast Food & Restaurants', 'Cafe & Beverages', 'cafe-beverages', 'Coffee, chai, shakes', '☕', 7, false),
  ('Fast Food & Restaurants', 'Chinese & Asian', 'chinese-asian', 'Chinese and Asian meals', '🥡', 8, false),
  ('Fast Food & Restaurants', 'Others / General', 'fast-food-restaurants-others', 'Other food items', '📦', 999, true)
ON CONFLICT (category, slug) DO NOTHING;
